### ISSUE TITLE
golang naming convention

### ISSUE THREAD

**Issue by wahyueko22** [novalagung/dasarpemrogramangolang#120]
sepertinya aku belum nemu artikel untuk golang naming convention

**Comment by novalagung** [comment]
iya belum ada. mas @wahyueko22 mau bantu menambahkan :-) ?

**Comment by novalagung** [comment]
saya akan masukan ke TODO issues, nnti agar bisa di track progress-nya. nnti akan coba saya lihat kira2 kapan saya sendiri bisa mengerjakan.

**Comment by wahyueko22** [comment]
boleh, caranya kontribusi gimana ya ? aku dah clone project tapi gak bisa buat branch baru.

**Comment by wahyueko22** [comment]
aku jaga lagi belajar golang mas @novalagung

**Comment by novalagung** [comment]
@wahyueko22 fork, clone ke local. untuk cara run-nya bagaimana coba cari di google cara run `gitbook-cli`
