### ISSUE TITLE
cd pipeline is not working

### ISSUE THREAD

**Issue by novalagung** [novalagung/dasarpemrogramangolang#155]
Somehow the cd pipeline is not working. need to resolve this as soon as possible. 

https://github.com/novalagung/dasarpemrogramangolang/actions/runs/757853854

**Comment by Kristories** [comment]
Is there a migration plan from Gitbook (which is being deprecated) @novalagung?

**Comment by novalagung** [comment]
@Kristories I haven't started to think about the migration thoroughly, but moving out from gitbook legacy is one thing I'd like to do in the future.

the reason I still use gitbook is that ebook files generation is pretty easy (pdf. mobi, epub). having a single source of truth for both web-based content and e-book files is one big advantage.

if there is a good alternative, I'd like to do some intensive research on it.
