### ISSUE TITLE
Prefer export & unexported instead of private & public

### ISSUE THREAD

**Issue by yofriadi** [novalagung/dasarpemrogramangolang#2]
Hi thank you for the book, but as the title says, in golang they dont do private or public method, maybe to differ from the oop language, or just like coroutine to goroutine.

**Comment by novalagung** [comment]
I think it's good idea.

**Comment by novalagung** [comment]
tbh the reason I use the terms (public and private) is because the target audience is pretty much a beginner with various programming language background, and the easiest analogy is by using the OOP modifiers.

anyway I think it's good idea. I shall do the changes in few days. thank you

**Comment by novalagung** [comment]
mas @yofriadi, sekadar menginfokan, bahwa sekarang source code ebook ini sudah di publish. silakan misal mas nya mau bantu untuk kontribusi :-)

**Comment by yofriadi** [comment]
nice, thank you mas, will do
