### ISSUE TITLE
[Bug] B.18. HTTP Basic Authentication

### ISSUE THREAD

**Issue by gedenata** [novalagung/dasarpemrogramangolang#41]
```bash
➜  ~ go version
go version go1.14 darwin/amd64
➜  ~ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/go/bin"
GOCACHE="/Users/Library/Caches/go-build"
GOENV="/Users/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vy/g05tg4j17r5_qgbn6dywcw0h0000gn/T/go-build012563067=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

<img width="981" alt="Screen Shot 2020-04-02 at 13 15 05" src="https://user-images.githubusercontent.com/1158185/78213026-ff6db700-74e3-11ea-8639-7eb4330a7e7b.png">

**Comment by gedenata** [comment]
<img width="797" alt="Screen Shot 2020-04-17 at 18 46 53" src="https://user-images.githubusercontent.com/1158185/79561366-d6504780-80db-11ea-8510-ff5ffd268193.png">

**Comment by sodrooome** [comment]
I have the same problem, dont know what it cause, i tried change the method but it's not working

**Comment by novalagung** [comment]
@gedenata @sodrooome fyi, https://github.com/ohmyzsh/ohmyzsh/issues/7058

> You need to escape the question mark, otherwise zsh thinks it is a globbing or wildcard character and tries to find files that match it (that's why it says no matches found). Using double or single quotes is enough: curl "wttr.in/Changsha?lang=zh".

I'm closing this issue
