### ISSUE TITLE
Kesalahan tulis

### ISSUE THREAD

**Issue by seno-ark** [novalagung/dasarpemrogramangolang#42]
Ijin melaporkan beberapa kesalahan tulis:

- C.32. SSO SAML (Service Provider)  
=> C.34. SSO SAML (Service Provider)
link: https://github.com/novalagung/dasarpemrogramangolang/blob/master/SUMMARY.md

- Mulai bab B1 hingga B6 kita akan mempelajari banyak aspek dalam framework Echo...  
=> Mulai bab C1 hingga C6 kita akan mempelajari banyak aspek dalam framework Echo...
link: https://github.com/novalagung/dasarpemrogramangolang/blob/master/C-1-echo-routing.md

- jika ada maka lakukan pengecekan pada error message-nya, jika ada keterangan "cancelled"  
=> jika ada maka lakukan pengecekan pada error message-nya, jika ada keterangan "canceled"  
link: https://github.com/novalagung/dasarpemrogramangolang/blob/master/B-23-server-handle-cancelled-http-request.md

- yg pertama sukses dan yang kedua adalah cancelled. Pesan request cancelled muncul ketika client http request dibatalkan.  
=> yg pertama sukses dan yang kedua adalah canceled. Pesan request canceled muncul ketika client http request dibatalkan.  
link: https://github.com/novalagung/dasarpemrogramangolang/blob/master/B-23-server-handle-cancelled-http-request.md

- Connection pool sangat penting dalam kaskus operasi data ...  
=> Connection pool sangat penting dalam kasus operasi data ...
link: https://github.com/novalagung/dasarpemrogramangolang/blob/master/D-1-insert-1mil-csv-record-into-db-in-a-minute.md

-  seperti yang sudah dibahas pada bab B-4, B-5, B-9, dan B-10.
Target link B-4 & B-5 not found:
B-4-render-html.html => B-4-template-render-html.html
B-5-render-html-partial.html => B-5-template-render-partial-html.html
link: https://github.com/novalagung/dasarpemrogramangolang/blob/master/C-5-echo-template-rendering.md

- Lebih jelasnya silakan baca kembali bab B-6 - Template Actions & Variables.
Target link B-6 not found
B-6-html-actions-variables.html => B-6-template-actions-variables.html
link: https://github.com/novalagung/dasarpemrogramangolang/blob/master/C-5-echo-template-rendering.md

- Tanda <- jika dituliskan di sebelah kanan channel, menandakan proses penerimaan data dari channel yang di kanan...  
=> Tanda <- jika dituliskan di sebelah kiri channel, menandakan proses penerimaan data dari channel yang di kanan  
link: https://github.com/novalagung/dasarpemrogramangolang/blob/master/30-channel.md

**Comment by novalagung** [comment]
terimakasih mas @seno-ark 

semua issues sudah saya resolve ya. cuman khusus untuk kata `cancellation`, tidak saya rubah, soalnya secara kata itu valid dalam ejaan inggris maupun british.

o iya misal mas nya mau kontribusi perbaikan bisa langsung juga lewat pull request juga.
