### ISSUE TITLE
[Ask] Missing chapter C.11

### ISSUE THREAD

**Issue by gedenata** [novalagung/dasarpemrogramangolang#49]
<img width="437" alt="Screen Shot 2020-04-23 at 11 11 13" src="https://user-images.githubusercontent.com/1158185/80054986-2f443380-8553-11ea-80d3-4433cc87c053.png">

**Comment by novalagung** [comment]
To be honest I myself forgot what chapter is removed at C.11.

But the reason why I don't adjust the number is to avoid SEO issues. all the links within this website are well tracked by Google. I just afraid that a slight adjustment (number order) might have big negative impact on the google search result.

let me think about new chapter that probably fits for this C.11. for now, I'm closing this issue.
