### ISSUE TITLE
New page: better configuration

### ISSUE THREAD

**Issue by novalagung** [novalagung/dasarpemrogramangolang#79]
also need to rethink the existing configuration (the one that uses JSON file). do we really need that? it is nice, but not very recommended I believe.

**Comment by bokunodev** [comment]
Json is already used for configuration files in many Go programs. Json is "simple" and "readable".
also to use Json ** no external dependencies required **.
If it's not Json, then what is the alternative?
I suggest ** .ini file** as an alternative

**Comment by novalagung** [comment]
@bokunodev 

JSON is not recommended on the production stage, especially when application managed using orchestration via Kubernetes. Every configuration needs to be in an os environment variable or in the memory storage like ETCD.

It'll be hard to manage the config seamlessly when the config is in a file. Like for example, what if I want to scale the current container into several instances with different port and config? I need to rewrite the .ini or the .json file on the file? No. definitely no.

I'm not talking about the self-preference version. I'm talking about real-world implementation. even docker-compose used env var to manage the config

**Comment by novalagung** [comment]
what I'm going to do probably improve the current JSON config, explain the pros and const (from DevOps perspective). and then create another one that uses OS env var. let's see.
