### ISSUE TITLE
New page: go redis example

### ISSUE THREAD

**Issue by novalagung** [novalagung/dasarpemrogramangolang#80]

**Comment by muhfaris** [comment]
udah ada yang ngerjain ini? @novalagung

**Comment by novalagung** [comment]
@muhfaris feel free to take it :-) thank you

**Comment by novalagung** [comment]
Untuk sample source code nya bisa di PR ke sini mas https://github.com/novalagung/dasarpemrogramangolang-example

**Comment by muhfaris** [comment]
great, thank you
