### ISSUE TITLE
[Typo] A.13.5. Penggunaan Keyword `break` & `continue`, page 45

### ISSUE THREAD

**Issue by gedenata** [novalagung/dasarpemrogramangolang#9]
<img width="764" alt="Screen Shot 2020-01-14 at 16 52 39" src="https://user-images.githubusercontent.com/1158185/72328662-4cfd3380-36ee-11ea-95aa-3356feaca4de.png">

Dengan melihat kode pada e-book tersebut, variable yang dipakai adalah `i` dan di poin nomor 4 menggunakan `m`.

**Comment by novalagung** [comment]
@gedenata terimakasih report nya
